import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const products = [
  {
    name: 'Soft Cloud Onesie',
    description: 'Ultra-soft organic cotton onesie perfect for newborns. Gentle on the most sensitive skin with envelope neckline for easy dressing.',
    price: 18.99,
    gender: 'UNISEX' as const,
    material: 'Organic Cotton',
    dye: 'Undyed (Natural)',
    size: 'NB',
    ageRange: '0–1 months',
    color: 'Cream',
    hexColor: '#F5F0E8',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&q=80',
    stock: 20,
    tags: ['organic', 'newborn', 'onesie'],
  },
  {
    name: 'Petal Pink Romper',
    description: 'Delicate floral-print romper in baby pink. GOTS-certified cotton with snap closures for easy nappy changes.',
    price: 24.99,
    gender: 'FEMALE' as const,
    material: 'GOTS Certified Cotton',
    dye: 'OEKO-TEX Certified Dye',
    size: '0-3m',
    ageRange: '0–3 months',
    color: 'Baby Pink',
    hexColor: '#FFB6C1',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&q=80',
    stock: 15,
    tags: ['floral', 'romper', 'pink'],
  },
  {
    name: 'Sky Blue Bodysuit Set',
    description: 'Three-pack bodysuits in powder blue with adorable cloud prints. Made from the softest organic cotton blend.',
    price: 29.99,
    gender: 'MALE' as const,
    material: 'Organic Cotton',
    dye: 'AZO-free Dye',
    size: '0-3m',
    ageRange: '0–3 months',
    color: 'Powder Blue',
    hexColor: '#B0D4E8',
    imageUrl: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500&q=80',
    stock: 12,
    tags: ['bodysuit', 'set', 'blue'],
  },
  {
    name: 'Bunny Print Sleepsuit',
    description: 'Cosy bamboo sleepsuit with a sweet bunny print. Temperature-regulating bamboo keeps baby comfortable all night.',
    price: 27.99,
    gender: 'UNISEX' as const,
    material: 'Bamboo',
    dye: 'Natural Plant-based Dye',
    size: '3-6m',
    ageRange: '3–6 months',
    color: 'Lavender',
    hexColor: '#D8B4E2',
    imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500&q=80',
    stock: 14,
    tags: ['sleepsuit', 'bamboo', 'bunny'],
  },
  {
    name: 'Strawberry Smock Dress',
    description: 'Sweet smocked dress with strawberry embroidery. Adjustable straps and breathable GOTS cotton for warm days.',
    price: 32.99,
    gender: 'FEMALE' as const,
    material: 'GOTS Certified Cotton',
    dye: 'OEKO-TEX Certified Dye',
    size: '3-6m',
    ageRange: '3–6 months',
    color: 'Rose Pink',
    hexColor: '#F48FB1',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80',
    stock: 10,
    tags: ['dress', 'smocked', 'floral'],
  },
  {
    name: 'Little Sailor Romper',
    description: 'Classic nautical romper in navy and white. Durable organic cotton built to keep up with active babies.',
    price: 27.99,
    gender: 'MALE' as const,
    material: 'Organic Cotton',
    dye: 'AZO-free Dye',
    size: '3-6m',
    ageRange: '3–6 months',
    color: 'Navy White',
    hexColor: '#B0C8E8',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&q=80',
    stock: 11,
    tags: ['nautical', 'romper', 'navy'],
  },
  {
    name: 'Daisy Chain Onesie',
    description: 'Sunshine yellow onesie with hand-printed daisy chain design. 100% organic cotton, certified dye.',
    price: 21.99,
    gender: 'FEMALE' as const,
    material: 'Organic Cotton',
    dye: 'OEKO-TEX Certified Dye',
    size: '6-9m',
    ageRange: '6–9 months',
    color: 'Butter Yellow',
    hexColor: '#FFF9C4',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&q=80',
    stock: 13,
    tags: ['onesie', 'yellow', 'daisy'],
  },
  {
    name: 'Elephant Adventure Tee',
    description: 'Playful elephant-print tee for little explorers. Soft GOTS cotton with reinforced stitching.',
    price: 19.99,
    gender: 'MALE' as const,
    material: 'GOTS Certified Cotton',
    dye: 'AZO-free Dye',
    size: '6-9m',
    ageRange: '6–9 months',
    color: 'Sky Blue',
    hexColor: '#90CAF9',
    imageUrl: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500&q=80',
    stock: 9,
    tags: ['tee', 'elephant', 'blue'],
  },
  {
    name: 'Soft Knit Cardigan',
    description: 'Classic cream cardigan in fine merino wool. Naturally temperature-regulating and machine washable.',
    price: 42.99,
    gender: 'UNISEX' as const,
    material: 'Merino Wool',
    dye: 'Undyed (Natural)',
    size: '6-9m',
    ageRange: '6–9 months',
    color: 'Ivory',
    hexColor: '#F5F0E8',
    imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500&q=80',
    stock: 8,
    tags: ['cardigan', 'merino', 'wool'],
  },
  {
    name: 'Rainbow Stripe Set',
    description: 'Bright rainbow stripe leggings and matching long-sleeve top. Stretchy organic cotton spandex blend.',
    price: 34.99,
    gender: 'FEMALE' as const,
    material: 'Organic Cotton Blend',
    dye: 'OEKO-TEX Certified Dye',
    size: '9-12m',
    ageRange: '9–12 months',
    color: 'Multicolour',
    hexColor: '#FFB6C1',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80',
    stock: 10,
    tags: ['set', 'rainbow', 'leggings'],
  },
  {
    name: 'Dino Explorer Set',
    description: 'Two-piece dino print set in sage green. Jogger pants and tee in soft organic cotton for active crawlers.',
    price: 36.99,
    gender: 'MALE' as const,
    material: 'Organic Cotton',
    dye: 'Natural Plant-based Dye',
    size: '12-18m',
    ageRange: '12–18 months',
    color: 'Sage Green',
    hexColor: '#A5C8A0',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&q=80',
    stock: 11,
    tags: ['set', 'dino', 'green'],
  },
  {
    name: 'Floral Twirl Dress',
    description: 'Twirly floral dress in soft lilac. Full lining, non-toxic dyes, and easy zip back closure.',
    price: 38.99,
    gender: 'FEMALE' as const,
    material: 'GOTS Certified Cotton',
    dye: 'OEKO-TEX Certified Dye',
    size: '12-18m',
    ageRange: '12–18 months',
    color: 'Lilac',
    hexColor: '#D8B4E2',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&q=80',
    stock: 9,
    tags: ['dress', 'floral', 'lilac'],
  },
  {
    name: 'Star & Moon Pyjama Set',
    description: 'Cosy bamboo pyjama set with glow-in-the-dark star print. Two-way zip for easy night changes.',
    price: 34.99,
    gender: 'UNISEX' as const,
    material: 'Bamboo',
    dye: 'AZO-free Dye',
    size: '18-24m',
    ageRange: '18–24 months',
    color: 'Powder Blue',
    hexColor: '#B0D4E8',
    imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500&q=80',
    stock: 12,
    tags: ['pyjamas', 'star', 'bamboo'],
  },
  {
    name: 'Cherry Blossom Top & Shorts',
    description: 'Matching cherry blossom top and wide-leg shorts. Breathable organic cotton, perfect for warm days.',
    price: 37.99,
    gender: 'FEMALE' as const,
    material: 'Organic Cotton',
    dye: 'OEKO-TEX Certified Dye',
    size: '18-24m',
    ageRange: '18–24 months',
    color: 'Baby Pink',
    hexColor: '#FFB6C1',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80',
    stock: 10,
    tags: ['set', 'cherry', 'pink'],
  },
  {
    name: 'Adventure Linen Outfit',
    description: 'Relaxed linen-cotton shirt and trousers set in sage. Naturally cool fabric for warm weather adventurers.',
    price: 44.99,
    gender: 'MALE' as const,
    material: 'Linen Cotton Blend',
    dye: 'Natural Plant-based Dye',
    size: '2T',
    ageRange: '2 years',
    color: 'Sage Green',
    hexColor: '#A5C8A0',
    imageUrl: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?w=500&q=80',
    stock: 8,
    tags: ['linen', 'set', 'toddler'],
  },
  {
    name: 'Princess Tulle Dress',
    description: 'Dreamy layered tulle dress in lavender with an organic cotton lining. Non-toxic dyes, fully washable.',
    price: 46.99,
    gender: 'FEMALE' as const,
    material: 'GOTS Certified Cotton',
    dye: 'OEKO-TEX Certified Dye',
    size: '3T',
    ageRange: '3 years',
    color: 'Lavender',
    hexColor: '#D8B4E2',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&q=80',
    stock: 7,
    tags: ['dress', 'tulle', 'toddler'],
  },
]

async function main() {
  console.log('Seeding database...')
  await prisma.product.deleteMany()
  for (const product of products) {
    await prisma.product.create({ data: product })
  }
  console.log(`Seeded ${products.length} products.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
